name: big_data_astro_dayla_tutorial

channels:
  - defaults

dependencies:
  - python>=3.6
  - ipython
  - anaconda
  - astropy
  - numpy
  - pandas>=0.19.0
  - scipy
  - h5py
  - seaborn>=0.8.1
  - scikit-learn>=0.19.1
  - pip>=18.0
  - pip:
    - GitPython
    - tables
